### ISSUE TITLE
Transormation retrival

### ISSUE THREAD

**Issue by muttistefano** [cmsaliba/coherent_point_drift_cuda#1]
Hi, 
is it possible to retrieve the transformatione between Xraw and Yraw?
How do i find it through the Traw output?
Thanks

**Comment by cmsaliba** [comment]
The transformed point set is T = Y + GW and thus the transformation is GW = T - Y. However, the transformation is performed in normalized coordinates, so to find GW you would first have to normalize the point sets T and Y.
